# Generated by Django 5.2.6 on 2025-09-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
    ]
